# roles/mphp/tasks/main.yml

- name: Copy PHP files to appropriate location
  copy:
    src: ../../../../php/mypage.php
    dest: /var/www/html/index.php

- name: Replace link in PHP file with correct IP address
  replace:
    path: /var/www/html/index.php
    regexp: 'http://.*?/'
    replace: 'http://{{ php_ip_address }}/'

- name: Install PHP and PHP-curl packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - php
    - php-curl

- name: Restart Apache service
  service:
    name: apache2
    state: restarted

