---
- name: setup partitions and files on EC2 instance
  hosts: all
  become: true
  vars:
    device_name: /dev/xvdh
    partitions:
      - number: 1
        mount_point: /var/log/audit
        size: 1GB
        fs_type: ext4
        opts: defaults
        part_start: "0%"
        part_end: "20%"
      - number: 2
        mount_point: /sysadmin
        size: 200MB
        fs_type: ext4
        opts: defaults
        part_start: "20%"
        part_end: "25%"
      - number: 3
        mount_point: /executives
        size: 500MB
        fs_type: ext4
        opts: defaults
        part_start: "25%"
        part_end: "35%"
      - number: 4
        mount_point: /analysts
        size: 200MB
        fs_type: ext4
        opts: "noexec,nosuid,nodev"
        part_start: "35%"
        part_end: "40%"

  tasks:
    - name: install packages
      ansible.builtin.package:
        name: parted
        state: present

    - name: create partitions
      community.general.parted:
        device: "{{ device_name }}"
        number: "{{ item.number }}"
        state: present
        part_start: "{{ item.part_start }}"
        part_end: "{{ item.part_end }}"
        flags: [ "lvm" ]
      loop: "{{ partitions }}"

    - name: Create filesystems on each partition
      community.general.filesystem:
        fstype: "{{ item.fs_type }}"
        dev: "{{ device_name }}{{ item.number }}"
      loop: "{{ partitions }}"

    - name: Create mount points
      ansible.builtin.file:
        path: "{{ item.mount_point }}"
        state: directory
      loop: "{{ partitions }}"

    - name: Mount the filesystems
      ansible.builtin.mount:
        path: "{{ item.mount_point }}"
        src: "{{ device_name }}{{ item.number }}"
        fstype: "{{ item.fs_type }}"
        opts: "{{ item.opts }}"
        state: mounted
      loop: "{{ partitions }}"
